name: Build Android and iOS
on:
  push:
    branches:
      - master
defaults:
  run:
    shell: bash
    working-directory: ./codebase/Dossier
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Run tests
        run: |
          npm test
